FROM node:20-bookworm

WORKDIR /browser_server

COPY ./package.json ./package.json
COPY ./package-lock.json ./package-lock.json

RUN npm ci

RUN npx -y playwright install --with-deps

COPY ./tsconfig.json ./tsconfig.json
COPY ./src/ ./src/

CMD ["npm", "run", "start"]
